[project]
name = "ml-pipeline"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "docker>=7.1.0",
    "google-cloud-aiplatform>=1.94.0",
    "ipython>=8.36.0",
    "kfp>=2.13.0",
    "mlflow>=2.22.0",
]
